import Head from "next/head";

// import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>PINKDOOR</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main></main>

      <footer></footer>
    </div>
  );
}
